// <auto-generated />
using System;
using System.Collections.Generic;
using AiWorkflow.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AiWorkflow.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260714223215_AddIntegrationsTables")]
    partial class AddIntegrationsTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AiWorkflow.Domain.Entities.Execution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("Logs")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("logs");

                    b.Property<string>("NodeRuns")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("node_runs");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("trigger");

                    b.Property<Guid>("TriggeredById")
                        .HasColumnType("uuid")
                        .HasColumnName("triggered_by_id");

                    b.Property<string>("TriggeredByName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("triggered_by_name");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_id");

                    b.Property<string>("WorkflowName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("workflow_name");

                    b.HasKey("Id")
                        .HasName("pk_executions");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_executions_status");

                    b.HasIndex("TriggeredById", "StartedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_executions_triggered_by_id_started_at");

                    b.HasIndex("WorkflowId", "StartedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_executions_workflow_id_started_at");

                    b.ToTable("executions", null, t =>
                        {
                            t.HasCheckConstraint("ck_executions_status", "status IN ('queued','running','success','failed','canceled')");

                            t.HasCheckConstraint("ck_executions_trigger", "trigger IN ('manual','webhook','cron','email','api')");
                        });
                });

            modelBuilder.Entity("AiWorkflow.Domain.Entities.Integration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("color");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<bool>("Popular")
                        .HasColumnType("boolean")
                        .HasColumnName("popular");

                    b.HasKey("Id")
                        .HasName("pk_integrations");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_integrations_name");

                    b.ToTable("integrations", (string)null);
                });

            modelBuilder.Entity("AiWorkflow.Domain.Entities.IntegrationAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ConnectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("connected_at");

                    b.Property<string>("EncryptedCredentials")
                        .HasColumnType("text")
                        .HasColumnName("credentials");

                    b.Property<Guid>("IntegrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("integration_id");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("label");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_integration_accounts");

                    b.HasIndex("IntegrationId")
                        .HasDatabaseName("ix_integration_accounts_integration_id");

                    b.HasIndex("UserId", "IntegrationId")
                        .HasDatabaseName("ix_integration_accounts_user_id_integration_id");

                    b.ToTable("integration_accounts", (string)null);
                });

            modelBuilder.Entity("AiWorkflow.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Browser")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("browser");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Device")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("device");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location");

                    b.Property<string>("Os")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("os");

                    b.Property<Guid?>("ReplacedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId", "RevokedAt")
                        .HasDatabaseName("ix_refresh_tokens_user_id_revoked_at");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("AiWorkflow.Domain.Entities.Template", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("author");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("color");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("difficulty");

                    b.Property<bool>("Featured")
                        .HasColumnType("boolean")
                        .HasColumnName("featured");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("icon");

                    b.Property<int>("Installs")
                        .HasColumnType("integer")
                        .HasColumnName("installs");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("NodeCount")
                        .HasColumnType("integer")
                        .HasColumnName("node_count");

                    b.Property<decimal>("Rating")
                        .HasColumnType("numeric(2,1)")
                        .HasColumnName("rating");

                    b.Property<bool>("RecentlyUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("recently_used");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.HasKey("Id")
                        .HasName("pk_templates");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_templates_category");

                    b.ToTable("templates", null, t =>
                        {
                            t.HasCheckConstraint("ck_templates_difficulty", "difficulty IN ('Beginner','Intermediate','Advanced')");
                        });
                });

            modelBuilder.Entity("AiWorkflow.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarColor")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("avatar_color");

                    b.Property<string>("Bio")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("bio");

                    b.Property<string>("Company")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("company");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("email_verified");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("job_title");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_role", "role IN ('Owner','Admin','Editor','Viewer')");
                        });
                });

            modelBuilder.Entity("AiWorkflow.Domain.Entities.UserPreferences", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<bool>("AccentAnimations")
                        .HasColumnType("boolean")
                        .HasColumnName("accent_animations");

                    b.Property<string>("DefaultView")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("default_view");

                    b.Property<string>("Density")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("density");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("language");

                    b.Property<bool>("SidebarCollapsed")
                        .HasColumnType("boolean")
                        .HasColumnName("sidebar_collapsed");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("theme");

                    b.HasKey("UserId")
                        .HasName("pk_user_preferences");

                    b.ToTable("user_preferences", (string)null);
                });

            modelBuilder.Entity("AiWorkflow.Domain.Entities.UserSettings", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<bool>("NotifyOnFailure")
                        .HasColumnType("boolean")
                        .HasColumnName("notify_on_failure");

                    b.Property<bool>("NotifyOnIntegration")
                        .HasColumnType("boolean")
                        .HasColumnName("notify_on_integration");

                    b.Property<bool>("NotifyOnSuccess")
                        .HasColumnType("boolean")
                        .HasColumnName("notify_on_success");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<bool>("WeeklyDigest")
                        .HasColumnType("boolean")
                        .HasColumnName("weekly_digest");

                    b.HasKey("UserId")
                        .HasName("pk_user_settings");

                    b.ToTable("user_settings", (string)null);
                });

            modelBuilder.Entity("AiWorkflow.Domain.Entities.Workflow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Edges")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("edges");

                    b.Property<int>("ExecutionCount")
                        .HasColumnType("integer")
                        .HasColumnName("execution_count");

                    b.Property<int>("FailureCount")
                        .HasColumnType("integer")
                        .HasColumnName("failure_count");

                    b.Property<bool>("Favorite")
                        .HasColumnType("boolean")
                        .HasColumnName("favorite");

                    b.Property<DateTimeOffset?>("LastRunAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_run_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Nodes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("nodes");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("SuccessCount")
                        .HasColumnType("integer")
                        .HasColumnName("success_count");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("trigger_type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Variables")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("node_variables");

                    b.HasKey("Id")
                        .HasName("pk_workflows");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_workflows_owner_id_not_archived")
                        .HasFilter("archived_at IS NULL");

                    b.HasIndex("Tags")
                        .HasDatabaseName("ix_workflows_tags");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Tags"), "gin");

                    b.HasIndex("OwnerId", "Status", "UpdatedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_workflows_owner_id_status_updated_at");

                    b.ToTable("workflows", null, t =>
                        {
                            t.HasCheckConstraint("ck_workflows_status", "status IN ('draft','active','inactive','error','archived')");

                            t.HasCheckConstraint("ck_workflows_trigger_type", "trigger_type IN ('manual','webhook','cron','email','api')");
                        });
                });

            modelBuilder.Entity("AiWorkflow.Domain.Entities.Execution", b =>
                {
                    b.HasOne("AiWorkflow.Domain.Entities.Workflow", null)
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_executions_workflows_workflow_id");
                });

            modelBuilder.Entity("AiWorkflow.Domain.Entities.IntegrationAccount", b =>
                {
                    b.HasOne("AiWorkflow.Domain.Entities.Integration", null)
                        .WithMany()
                        .HasForeignKey("IntegrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_integration_accounts_integrations_integration_id");

                    b.HasOne("AiWorkflow.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_integration_accounts_users_user_id");
                });

            modelBuilder.Entity("AiWorkflow.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("AiWorkflow.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");
                });

            modelBuilder.Entity("AiWorkflow.Domain.Entities.UserPreferences", b =>
                {
                    b.HasOne("AiWorkflow.Domain.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("AiWorkflow.Domain.Entities.UserPreferences", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_preferences_users_user_id");
                });

            modelBuilder.Entity("AiWorkflow.Domain.Entities.UserSettings", b =>
                {
                    b.HasOne("AiWorkflow.Domain.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("AiWorkflow.Domain.Entities.UserSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_settings_users_user_id");
                });

            modelBuilder.Entity("AiWorkflow.Domain.Entities.Workflow", b =>
                {
                    b.HasOne("AiWorkflow.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflows_users_owner_id");
                });
#pragma warning restore 612, 618
        }
    }
}
